from numpy import zeros, sin, pi
from numpy import linspace, array
from scipy.integrate import odeint

class DynamicSystem:
    """Dynamic System class.

    """

    def __init__(self):

        # parameter names and their values
        self.parameters = {'g':9.81,
                           'l':1.,
                           'm':1.}
        # state names and their initial conditions
        self.states = {'theta':(0, 0.),
                       'omega':(1, 0.),
                       'thetap':(2, 0.),
                       'omegap':(3, 0.)}
        # numerical integration parameters
        self.numint = {'ti':0.,
                       'tf':10.}

    def f(self, x, t, params):

        # defines the parameters from the attribute
        for parameter, value in params.items():
            exec(parameter + ' = ' + str(value))

        theta = x[0]
        omega = x[1]

        z = zeros(1)
        z[0] = sin(theta)

        torque = inputs(t)[0]

        thetap = omega
        omegap = -g/l*z[0] + torque/(m*l*l)

        f = zeros(2)
        f[0] = thetap
        f[1] = omegap

        params[3] = z[0]
        return f

    def inputs(self, t):
        print pi
        print t
        torque = 10*sin(2*pi*t + pi/6)
        print torque
        inputs = zeros(1)
        inputs[0] = torque
        return inputs

    def simulate(self, f, numint):
        t = linspace(numint['ti'], numint['tf'], 100)
        # Using a nested list so that we pass parameters via odeint, and allow those
        # parameters to be modified within our ODE function.  This would be used to
        # modify the z values generated by Autolev, and 
        params = [g, l, m, z]

        x = zeros((len(t), 2))
        x[0] = array([0.1, 0.2])
        #print x

        for i in range(len(t)-1):
            t_int = [t[i], t[i+1]]

            test = odeint(pendulum_f, x[i], t_int, args=(params,))
            # causes z element of params to be modified using the latest state estimate
            pendulum_f(test[1,:], t[i+1], params)
            x[i+1] = test[1,:]
            # this guy is being calculated inside of pendulum_f
            print "params =", params[3]
            # this guy is being calculated right now:w
            print "sin(x[i + 1][0] =", sin(x[i + 1, 0])
